import cv2
cat = cv2.imread("./image/cat.jpg")
b,g,r = cv2.split(cat)
cv2.imshow("cat",cat)
cat_rgb=cv2.merge((r,g,b))
cat_bgr=cv2.merge([b,g,r])
cat_grb=cv2.merge([g,r,b])
cv2.imshow("cat_rgb",cat_rgb)
cv2.imshow("cat_bgr",cat_bgr)
cv2.imshow("cat_grb",cat_grb)
cv2.waitKey()
cv2.destroyAllWindows()